### ISSUE TITLE
Block Data

### ISSUE THREAD

**Issue by mastercoms** [GlowstoneMC/1.13-board#3]
*This issue is part of the 1.13.x compatibility Epic.*

All contributions are subject to the [Glowstone CLA](https://glowstone.net/cla). **In short, contributions must not contain any content (code or otherwise) copied from,
inspired by or based upon content from Mojang or third-party projects that are based on such content (CraftBukkit, Spigot, Forge, ...).**

---

**Description**:

In 1.13 , all the different byte and short metadata to describe block information was scrapped, and replaced with properties. These are stored in block states, with block data. These properties are defined within data packs. We need to:

- [x] Convert `BlockData` to numerical IDs #27
- [x] Implement `BlockData` for each block type/property #28
- [ ] Change `setType`, `setData`, `setTypeAndData` calls to use `BlockData`  #30
- [ ] Implement `BlockData` in `ChunkSection` #31

**Reference Documentation**:

* https://papermc.io/javadocs/paper/1.13/org/bukkit/block/data/package-summary.html
* https://minecraft.gamepedia.com/Java_Edition_data_values#Block_states
* https://minecraft.gamepedia.com/Java_Edition_1.13/Flattening#Block_and_Item_IDs
* https://pokechu22.github.io/Burger/1.13.2.html
* https://wiki.vg/Data_Generators

**Relevant Code**:

* https://github.com/GlowstoneMC/Glowstone/tree/1.13/src/main/java/net/glowstone/block/data
* https://github.com/GlowstoneMC/Glowstone/tree/1.13/src/main/java/net/glowstone/block/flattening
* https://bugs.mojang.com/secure/attachment/151784/the_flattening.txt

**Related to:**

#4
