### ISSUE TITLE
Data packs

### ISSUE THREAD

**Issue by mastercoms** [GlowstoneMC/1.13-board#4]
*This issue is part of the 1.13.x compatibility Epic.*

All contributions are subject to the [Glowstone CLA](https://glowstone.net/cla). **In short, contributions must not contain any content (code or otherwise) copied from,
inspired by or based upon content from Mojang or third-party projects that are based on such content (CraftBukkit, Spigot, Forge, ...).**

---

**Description**:

Most of Minecraft's IDs were moved over to a namespaced data pack system, where all game data is defined within JSON files. Glowstone should be able to read these JSON files from a base server data directory, as well as allow for data packs within worlds, as in vanilla. Glowstone should then use these JSON files for all block, item, recipe, etc initialization, rather than hard coded types. This is a tricky task, considering our need for API support in Bukkit, which does not seem to play completely well with the modular and data based approach in data packs, and extra internal data that we need for each type which is not in the data pack format.

- [x] Have a way to automatically get vanilla data packs without redistribution. This will likely involve downloading the Minecraft server automatically and running it for generating data reports. #5 
- [x] Replace built in recipes with recipes from data packs #6 
- [ ] Add data pack serialization paths to base server folder and per world #8
- [ ] Item/Block registry #7
- [x] State/property registry #3, #28 
- [x] Tag registry #2, #11
- [ ] Advancement registry #12
- [ ] Command registry (Brigadier) #13 

Most of these have their own issues for individual implementation with more detail.

**Reference Documentation**:

* https://wiki.vg/Data_Generators
* https://minecraft.gamepedia.com/Data_pack
* https://github.com/GlowstoneMC/Glowstone/blob/1.13/src/main/java/net/glowstone/inventory/crafting/CraftingManager.java

**Relevant Code**:

* https://github.com/GlowstoneMC/unflattening
